package cep;
import com.ftn.sbnz.model.models.IdealPlace;
import com.ftn.sbnz.model.models.Place;
import com.ftn.sbnz.model.models.Score;
import java.util.List;

rule "cena_rule"
    when
        $ip : IdealPlace()
        $s : Score()
        Place($ip.getMin_cena() <= getProsecna_cena() && $ip.getMax_cena() >= getProsecna_cena())
    then
        modify($s){setFirst(true)}
end

rule "temperatura_rule"
    when
        $ip : IdealPlace()
        $s : Score()
        Place($ip.getMin_temperatura() <= getProsecna_temperatura() && $ip.getMax_temperatura() >= getProsecna_temperatura())
    then
        modify($s){setSecond(true)}
end

rule "nocni_zivot_rule"
    when
        $ip : IdealPlace()
        $s : Score()
        Place($ip.getNocni_zivot() <= getNocni_zivot())
    then
        modify($s){setThird(true)}
end

rule "urbanost_rule"
    when
        $ip : IdealPlace()
        $s : Score()
        Place($ip.getUrbanost() >= getUrbanost())
    then
        modify($s){setFourth(true)}
end

rule "luksuz_rule"
    when
        $ip : IdealPlace()
        $s : Score()
        Place($ip.getLuksuz() <= getLuksuz())
    then
        modify($s){setSixth(true)}
end

rule "gradski_prevoz_rule"
    when
        $ip : IdealPlace()
        $s : Score()
        Place($ip.getDostupnost_gradskog_prevoza() == getDostupnost_gradskog_prevoza())
    then
        modify($s){setSeventh(true)}
end

rule "vodene_površine_rule"
    when
        $ip : IdealPlace()
        $s : Score()
        Place($ip.getVodene_povrsine() == getVodene_povrsine())
    then
        modify($s){setEighth(true)}
end

rule "hrana_rule"
    when
        $ip : IdealPlace()
        $s : Score()
        Place($ip.getHrana() >= getHrana())
    then
        modify($s){setNinth(true)}
end

rule "skijalista_rule"
    when
        $ip : IdealPlace()
        $s : Score()
        Place($ip.getSkijalista() == getSkijalista())
    then
        modify($s){setTenth(true)}
end
