package cep;
import com.ftn.sbnz.model.models.IdealPlace;
import com.ftn.sbnz.model.models.Place;
import com.ftn.sbnz.model.models.Score;
import com.ftn.sbnz.model.models.RuleChain;
import java.util.List;

rule "chain-1"
    when
        IdealPlace()
        Score()
        Place()
        $rc: RuleChain(getRulechain() == 0)
    then
        modify($rc){setRulechain(1)}
end

rule "chain-2"
    when
        $rc: RuleChain(getRulechain() == 1)
    then
        modify($rc){setRulechain(2)}
end

rule "chain-3"
    when
        $rc: RuleChain(getRulechain() == 2)
    then
        modify($rc){setRulechain(3)}
end

rule "chain-4"
    when
        $rc: RuleChain(getRulechain() == 3)
    then
        modify($rc){setRulechain(4)}
end

rule "cena_rule"
    when
        $ip : IdealPlace()
        $s : Score()
        RuleChain(getRulechain() == 0)
//        Place()
        $rc: RuleChain(getRulechain() == 0)
        Place($ip.getMin_cena() <= getProsecna_cena(), $ip.getMax_cena() >= getProsecna_cena())
    then
        $s.setFirst(true);
end

rule "temperatura_rule"
    when
        $ip : IdealPlace()
        $s : Score()
        $rc: RuleChain(getRulechain() == 1)
        Place($ip.getMin_temperatura() <= getProsecna_temperatura(), $ip.getMax_temperatura() >= getProsecna_temperatura())
    then
        $s.setSecond(true);
end

rule "nocni_zivot_rule"
    when
        $ip : IdealPlace()
        $s : Score()
        $rc: RuleChain(getRulechain() == 2)
        Place($ip.getMin_nocni_zivot() <= getNocni_zivot(), $ip.getMax_nocni_zivot() >= getNocni_zivot())
    then
        $s.setThird(true);
end

rule "urbanost_rule"
    when
        $ip : IdealPlace()
        $s : Score()
        $rc: RuleChain(getRulechain() == 3)
        Place($ip.getMin_urbanost() <= getUrbanost(), $ip.getMax_urbanost() >= getUrbanost())
    then
        $s.setFourth(true);
end

rule "luksuz_rule"
    when
        $ip : IdealPlace()
        $s : Score()
        RuleChain(getRulechain() == 4)
        Place($ip.getMin_luksuz() <= getLuksuz(), $ip.getMax_luksuz() >= getLuksuz())
    then
        $s.setFifth(true);
end

rule "gradski_prevoz_rule"
    when
        $ip : IdealPlace()
        $s : Score()
        Place($ip.getDostupnost_gradskog_prevoza() == getDostupnost_gradskog_prevoza())
    then
        $s.setSixth(true);
end

rule "vodene_površine_rule"
    when
        $ip : IdealPlace()
        $s : Score()
        Place($ip.getVodene_povrsine() == getVodene_povrsine())
    then
        $s.setSeventh(true);
end

rule "hrana_rule"
    when
        $ip : IdealPlace()
        $s : Score()
        Place($ip.getMin_hrana() <= getHrana(), $ip.getMax_hrana >= getHrana())
    then
        $s.setEighth(true);
end

rule "skijalista_rule"
    when
        $ip : IdealPlace()
        $s : Score()
        Place($ip.getSkijalista() == getSkijalista())
    then
        $s.setNinth(true);
end
